import type { Metadata } from "next";
import {Host_Grotesk } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
const font = Host_Grotesk({
  subsets:['latin','latin-ext']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className}  antialiased`}
      >
        <ClerkProvider>
          
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
